<?php


 /**
  * Horario Value Object.
  * This class is value object representing database table Horario
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */




class Horario {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    var $idProfesor;
    var $dia;
    var $hora;
    var $grupo;
    var $aula;
    var $guardia;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    function Horario () {

    }

    /* function Horario ($idProfesorIn, $diaIn, $horaIn) {

          $this->idProfesor = $idProfesorIn;
          $this->dia = $diaIn;
          $this->hora = $horaIn;

    } */


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    function getIdProfesor() {
          return $this->idProfesor;
    }
    function setIdProfesor($idProfesorIn) {
          $this->idProfesor = $idProfesorIn;
    }

    function getDia() {
          return $this->dia;
    }
    function setDia($diaIn) {
          $this->dia = $diaIn;
    }

    function getHora() {
          return $this->hora;
    }
    function setHora($horaIn) {
          $this->hora = $horaIn;
    }

    function getGrupo() {
          return $this->grupo;
    }
    function setGrupo($grupoIn) {
          $this->grupo = $grupoIn;
    }

    function getAula() {
          return $this->aula;
    }
    function setAula($aulaIn) {
          $this->aula = $aulaIn;
    }

    function getGuardia() {
          return $this->guardia;
    }
    function setGuardia($guardiaIn) {
          $this->guardia = $guardiaIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    function setAll($idProfesorIn,
          $diaIn,
          $horaIn,
          $grupoIn,
          $aulaIn,
          $guardiaIn) {
          $this->idProfesor = $idProfesorIn;
          $this->dia = $diaIn;
          $this->hora = $horaIn;
          $this->grupo = $grupoIn;
          $this->aula = $aulaIn;
          $this->guardia = $guardiaIn;
    }


    /** 
     * hasEqualMapping-method will compare two Horario instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    function hasEqualMapping($valueObject) {

          if ($valueObject->getIdProfesor() != $this->idProfesor) {
                    return(false);
          }
          if ($valueObject->getDia() != $this->dia) {
                    return(false);
          }
          if ($valueObject->getHora() != $this->hora) {
                    return(false);
          }
          if ($valueObject->getGrupo() != $this->grupo) {
                    return(false);
          }
          if ($valueObject->getAula() != $this->aula) {
                    return(false);
          }
          if ($valueObject->getGuardia() != $this->guardia) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    function toString() {
        $out = $this->getDaogenVersion();
        $out = $out."\nclass Horario, mapping to table Horario\n";
        $out = $out."Persistent attributes: \n"; 
        $out = $out."idProfesor = ".$this->idProfesor."\n"; 
        $out = $out."dia = ".$this->dia."\n"; 
        $out = $out."hora = ".$this->hora."\n"; 
        $out = $out."grupo = ".$this->grupo."\n"; 
        $out = $out."aula = ".$this->aula."\n"; 
        $out = $out."guardia = ".$this->guardia."\n"; 
        return $out;
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    function clone() {
        $cloned = new Horario();

        $cloned->setIdProfesor($this->idProfesor); 
        $cloned->setDia($this->dia); 
        $cloned->setHora($this->hora); 
        $cloned->setGrupo($this->grupo); 
        $cloned->setAula($this->aula); 
        $cloned->setGuardia($this->guardia); 

        return $cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    function getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

?>